version: '3.7'

services:
    deployment:
        build: ./docker/deployment
        container_name: deployment-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
            - ./ssh-keys:/home/node/.ssh
        ports:
            - '${INTERFACE}:${DEPLOYMENT_WEB_PORT}:${DEPLOYMENT_WEB_PORT}'
        networks:
            - bitrix
        depends_on:
            - nginx
        restart: always
        environment:
          DEPLOYMENT_WEB_PORT: ${DEPLOYMENT_WEB_PORT}
    php:
        build: ./docker/php
        container_name: php-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
            - ./logs/php:/var/log/php
        ports:
            - '${INTERFACE}:${HOST_PORT_PHP}:${CONTAINER_PORT_PHP}'
        depends_on:
            - mysql
        networks:
            - bitrix
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
            - ./data/memcached:/var/lib/memcached
            - ./logs/memcached:/var/log/memcached
        ports:
            - '${INTERFACE}:${HOST_PORT_MEMCACHED}:${CONTAINER_PORT_MEMCACHED}'
        networks:
            - bitrix
        restart: always
    nginx:
        build: ./docker/nginx
        container_name: nginx-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
            - ./logs/nginx:/var/log/nginx
        ports:
            - '${INTERFACE}:${HOST_PORT_HTTP}:${CONTAINER_PORT_HTTP}'
            - '${INTERFACE}:${HOST_PORT_HTTPS}:${CONTAINER_PORT_HTTPS}'
        depends_on:
            - source
            - php
        networks: 
            - bitrix
        restart: always
    mysql:
        build: docker/mysql
        container_name: mysql-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        ports:
            - '${INTERFACE}:${HOST_PORT_MYSQL}:${CONTAINER_PORT_MYSQL}'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
        networks:
            - bitrix
        restart: always
    nodejs:
        build: docker/nodejs
        container_name: nodejs-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
        networks:
            - bitrix
    source:
        image: alpine:latest
        container_name: source-${PROJECT_NAME}
        volumes:
            - ./:/var/www/project
            - ./data/mysql:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - ./logs/memcached:/var/log/memcached
            - ./logs/nginx:/var/log/nginx
            - ./logs/php:/var/log/php
            - ./logs/mysql:/var/log/mysql
        networks:
            - bitrix
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 12.100.0.0/24
